address: "Glasglow Dr 40 Fe 72."
tel: "1115550001"
fax: "190-4509-494"
email: "contact@example.com"
facebook: "Facebook"
twitter: "Twitter"
google: "Google+"
length_digit_6: 6
length_digit_255: 255
vi: "vi"
en: "en"
expired_password_time: 2
items_per_page: 8
